CREATE TABLE CHARACTERS (
	CHARACTER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CHARACTER_NAME TEXT,
	CHARACTER_SPRITE TEXT);
	
CREATE TABLE CHARACTERS_ACTIONS (
	CHARACTER_ACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CHARACTER_ID INTEGER,
	CHARACTER_ACTION_SCRIPT TEXT);
	
CREATE TABLE LOCATION_1 (
	LOCATION_OBJECT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CHARACTER_ID INTEGER,
	SPAWN_POS_X INTEGER,
	SPAWN_POS_Y INTEGER);